language: java
jdk: openjdk8
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: KGEgfPJrxHW1VxbbYmWl1oRnKfVroH3q8RxKQtT3VE7aMn9JfJdtpthOZft321lg/2Pg6fIQdEs7vwd8nFE45kyKtkupzLGSjfI6hxcwc7ryBi2ZWOmZm3zml29KKec19q/DdbcbaAGuIsNxizEUxHGLhDh5YWmQ092QNmrlaElob5rDDtMCloGDVC5/M0rJrp05zlDCrkClrLziJpsU54Mx2QTNRPckARUOzKW5lSZEPfOzp55sLamHEDDHcJlbZcrMZFOAGYEC29NEqXLK5qUAHscnGwfdwLVPso6XMKT3IyFyz4E9qUmr2DUNFh0vHWXdY06QejxcqEs5ZCRKffv+IXNzckKU3ZbjbEl9dGAUqmA4rO6bSzpDhEgfZZL2/P5IkD0YSXwCWS0a4R1p7L89qpKhqaHucSOifeZv3e7CB17E7BTz57gjJCH0I2NfZ6/uDuEECPwdhIQmkDYaTJ9eTW+A6b81FRugkU9hEojbvES6zgvYgBEzL1sYKCg+vLFxR5WjPGhdDc+ekPuiqa8pR8Os0mAIRZ14eVF6nK4vysKFBH9CpE0rqAullovYIHnLztP/Soe+lCNw/Z3rIZIhdhye/wfZ0OWd7eBkweyESpz/YIyLiFYVUwm3VDPfjIbgm72DFJiEHiinxrs2Bd/vIGhZ0Fs1Xh+CfY2MAqk=
  - secure: YEAiabLacK1xAw6MR/7Ph50iMnzTDPWEZ8a9iXdOg7vb0nJW/5AmtnOVV9Pg49KaOCNZHKED9zxy7+OFQH91363wZdkZD29nZlDi1d5p+/M7VqMyJqjanzOx3yJh66lStSQcJnOZgjzmobBT9oYgqv2rzifVdDmrZhjWYS0Njzc8u5pj5stQPL0Q64UVi7BRVoakg2UAOS3U7WBkWsL9xHRBVhZ1b44a1dBUsSpQ6bHVzhrK+DCrsn2mnosBKlkHuRG2BQwKJ4YbFeczltDp88MNMIExLxQn1flLjpkVqucEtbbXoXX1DKXAYqjhY/SoYfmJbs12tOpb83/UO5go7O8u8/lbU78ecqEL0FVkW70ABzJDhvBWUld4Sdn2JrvYtVjRfnvR/YAO4me8J65hvNHQpqNqGkr2P+eOSARYTkDUKc9e+2GhkemK0LBwWoEyKpKYahH+ic8NJInGL7GvKyY/QuiokVqHlhM5bDXSWyMVeDvJz4pdF2aOb0wyPXYqGwtm1XOZQ1MgJ+u/UyA61awpAfqkoUduN2a5Aycsz5fLJe5hxjIz75BHEyJJVqX8tt4H0EdsZFmLvyXHHCO98paBaB1f6MiwFPGb4xqVaGcgpgt/GgRwWHV16mrzuRwuplp2PbYPeEXm9SLBlRT40DDE2GYVjrZsKOiOa/xpqus=
install: true
script: mvn -B test -P gdsc-test-examples checkstyle:check spotbugs:check
after_success:
- mvn process-sources jacoco:report coveralls:report
deploy:
  provider: script
  script:
  - if grep --quiet '<version>.*SNAPSHOT</version>' pom.xml; then mvn deploy -P snapshot-release
    --settings deploy/settings.xml -DskipTests=true; fi
  skip_cleanup: true
  on:
    branch: master
