name: Java CI

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build
      run: .github/build.sh
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Build coverage
      run: mvn -B --no-transfer-progress -P jacoco,gdsc-test-doc jacoco:report-aggregate -pl gdsc-test-doc
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./gdsc-test-doc/target/site/jacoco-aggregate/jacoco.xml
