name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: 'maven'
        # these values cause the plugin to set up the Maven settings.xml file
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: SONATYPE_USERNAME # env variable for username in deploy
        server-password: SONATYPE_PASSWORD # env variable for token in deploy
    - name: Get version
      run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Build
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: mvn -V -B --no-transfer-progress -P jacoco spotbugs:check verify
    - name: Deploy SNAPSHOT
      # must run directly after 'Build'
      if: matrix.java == 8 && github.repository == 'aherbert/gdsc-test' && github.ref_name == 'master' && contains(env.PROJECT_VERSION, 'SNAPSHOT')
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: >
        mvn -V -B --no-transfer-progress -Psnapshot-release deploy -Dgpg.skip 
        -DskipTests -Drat.skip -Djacoco.skip -Dcyclonedx.skip -Dspotbugs.skip -Dspdx.skip -Dpmd.skip
    - name: Build coverage
      run: mvn -B --no-transfer-progress -P jacoco,gdsc-test-doc jacoco:report-aggregate
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./gdsc-test-doc/target/site/jacoco-aggregate/jacoco.xml
